"""A deterministic synthetic stream source (v2 §15).

Produces packets, samples and observations from a recorded seed, so the same
seed always yields byte-identical raw tables. It generates no scientific signal
and encodes no physiological meaning: the values are a reproducible pattern, and
nothing downstream may read them as measurements of anything.

`SyntheticSource` itself is synchronous and knows nothing about asynchrony,
device fan-in, scheduling or back-pressure: it only produces valid rows.
`SyntheticStreamSource` at the bottom of this module adapts it to the CL-003
recorder's source contract, which is where those four properties live.
"""

import random
import struct
import threading
from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any

from consciousness_lab.session.model import (
    Acquisition,
    AcquisitionBackend,
    AppliesTo,
    Channel,
    ClaimStatus,
    HardwareClaim,
    HardwareVerification,
    ObservationKind,
    ObservationProvenance,
    RawCaptureLevel,
    SampleLayout,
    StreamDescriptor,
)
from consciousness_lab.session.recorder import PacketSink, SourceDisconnectedError, SourcePacket
from consciousness_lab.storage.chunk_writer import PendingChunk

MONOTONIC_CLOCK_ID = "CLOCK_MONOTONIC"
UTC_CLOCK_ID = "CLOCK_REALTIME"


@dataclass(frozen=True)
class SyntheticStreamSpec:
    """Everything that varies between the streams a test wants."""

    stream_id: str
    capture_level: RawCaptureLevel
    n_channels: int = 2
    samples_per_packet: int = 4
    layout: SampleLayout = SampleLayout.DENSE_FIXED_LIST
    device_alias: str = "synthetic-01"
    device_kind: str = "synthetic"
    modality: str = "synthetic"
    backend_name: str = "consciousness_lab.synthetic"
    #: Whether to emit a device-time observation per packet.
    emit_device_time: bool = True
    #: Whether to emit a counter observation per packet.
    emit_counter: bool = True


def build_descriptor(spec: SyntheticStreamSpec) -> StreamDescriptor:
    """A descriptor honest about being synthetic and unverified."""
    preserved = spec.capture_level is RawCaptureLevel.TRANSPORT_PAYLOAD
    boundary = {
        RawCaptureLevel.TRANSPORT_PAYLOAD: "synthetic transport bytes are generated and preserved",
        RawCaptureLevel.LIBRARY_DECODED: (
            "simulates a backend that decoded before our boundary; no transport bytes exist"
        ),
        RawCaptureLevel.SYNTHETIC: (
            "generated by this repository; there is no device and no transport"
        ),
    }[spec.capture_level]
    return StreamDescriptor(
        stream_id=spec.stream_id,
        device_alias=spec.device_alias,
        device_kind=spec.device_kind,
        modality=spec.modality,
        layout=spec.layout,
        channels=[
            Channel(index=i, channel_id=f"ch{i}", unit=None, dtype="float32")
            for i in range(spec.n_channels)
        ],
        acquisition=Acquisition(
            backend=AcquisitionBackend(name=spec.backend_name, version="0", adapter_version="0"),
            raw_capture_level=spec.capture_level,
            transport_payload_preserved=preserved,
            decode_boundary=boundary,
            provenance=HardwareClaim(
                value=None, status=ClaimStatus.ASSUMED, source="synthetic source"
            ),
        ),
        nominal_sample_rate_hz=HardwareClaim(
            value=None, status=ClaimStatus.ASSUMED, source="synthetic source"
        ),
        channel_layout_provenance=HardwareClaim(
            value=None, status=ClaimStatus.ASSUMED, source="synthetic source"
        ),
        hardware_verification=HardwareVerification(),
    )


@dataclass
class SyntheticSource:
    """Generates deterministic chunks for one stream."""

    spec: SyntheticStreamSpec
    seed: int = 0
    _packet_seq: int = 0
    _monotonic_ns: int = 1_000_000_000
    _utc_ns: int = 1_787_923_530_123_456_789
    _rng: random.Random = field(init=False)

    def __post_init__(self) -> None:
        self._rng = random.Random(self.seed)

    def next_chunk(self, n_packets: int) -> PendingChunk:
        """Produce one chunk's worth of rows."""
        pending = PendingChunk()
        preserved = self.spec.capture_level is RawCaptureLevel.TRANSPORT_PAYLOAD
        for _ in range(n_packets):
            packet_seq = self._packet_seq
            self._packet_seq += 1
            self._monotonic_ns += 4_000_000
            self._utc_ns += 4_000_000

            values: list[list[float]] = []
            for sample_index in range(self.spec.samples_per_packet):
                row = [round(self._rng.uniform(-1.0, 1.0), 6) for _ in range(self.spec.n_channels)]
                values.append(row)
                if self.spec.layout is SampleLayout.DENSE_FIXED_LIST:
                    pending.samples.append(
                        {
                            "packet_seq": packet_seq,
                            "sample_index_in_packet": sample_index,
                            "values": row,
                        }
                    )
                else:
                    for channel_index, value in enumerate(row):
                        pending.samples.append(
                            {
                                "packet_seq": packet_seq,
                                "sample_index_in_packet": sample_index,
                                "channel_id": f"ch{channel_index}",
                                "value": float(value),
                            }
                        )

            if preserved:
                # No payload_ref is produced: v2 removed it, and the frame the
                # writer emits already carries this packet_seq (§5).
                blob = b"".join(struct.pack("<f", v) for row in values for v in row)
                pending.payloads.append((packet_seq, blob))

            pending.packets.append(
                {
                    "packet_seq": packet_seq,
                    "host_arrival_monotonic_ns": self._monotonic_ns,
                    "host_arrival_utc_ns": self._utc_ns,
                    "host_arrival_monotonic_clock_id": MONOTONIC_CLOCK_ID,
                    "host_arrival_utc_clock_id": UTC_CLOCK_ID,
                    "n_samples": self.spec.samples_per_packet,
                    "decode_status": "ok",
                }
            )

            if self.spec.emit_device_time:
                pending.observations.append(
                    _observation(
                        packet_seq,
                        kind=ObservationKind.TIME,
                        name="synthetic.device_time",
                        value_type="float64",
                        value_f64=float(packet_seq) * 0.004,
                        unit="s",
                        clock_id="synthetic_device_clock",
                    )
                )
            if self.spec.emit_counter:
                pending.observations.append(
                    _observation(
                        packet_seq,
                        kind=ObservationKind.COUNTER,
                        name="synthetic.packet_counter",
                        value_type="uint64",
                        value_u64=packet_seq,
                        unit=None,
                        clock_id=None,
                    )
                )
        return pending


def _observation(
    packet_seq: int,
    *,
    kind: ObservationKind,
    name: str,
    value_type: str,
    unit: str | None,
    clock_id: str | None,
    value_i64: int | None = None,
    value_u64: int | None = None,
    value_f64: float | None = None,
    value_str: str | None = None,
) -> dict[str, Any]:
    """One observation row. ``applies_to`` is ``unknown`` and ``status`` is
    ``assumed``, which is the honest state for every device in this study."""
    return {
        "packet_seq": packet_seq,
        "sample_index_in_packet": None,
        "kind": kind.value,
        "name": name,
        "value_type": value_type,
        "value_i64": value_i64,
        "value_u64": value_u64,
        "value_f64": value_f64,
        "value_str": value_str,
        "unit": unit,
        "clock_id": clock_id,
        "applies_to": AppliesTo.UNKNOWN.value,
        "provenance": ObservationProvenance.LIBRARY_PROVIDED.value,
        "status": ClaimStatus.ASSUMED.value,
    }


@dataclass
class SyntheticStreamSource:
    """Adapts :class:`SyntheticSource` to the CL-003 recorder source contract.

    Deliberately thin. The recorder is what is under test; this only has to be
    a well-behaved source: it produces a fixed number of packets, honours the
    stop signal between packets, and hands each packet over one at a time so
    the recorder — not the source — decides where chunk boundaries fall.

    ``fail_after`` and ``disconnect_after`` exist so the abnormal termination
    paths can be exercised without a device. They simulate nothing about real
    hardware and prove nothing about it (``AGENTS.md`` §7).
    """

    spec: SyntheticStreamSpec
    n_packets: int
    seed: int = 0
    #: Raise ``RuntimeError`` after this many packets, to exercise FAILED.
    fail_after: int | None = None
    #: Raise ``SourceDisconnectedError`` after this many packets, to exercise
    #: DISCONNECTED.
    disconnect_after: int | None = None
    #: Called after each packet is submitted. A test seam for interleaving; it
    #: is never used to fabricate timing.
    after_packet: Callable[[], None] | None = None
    _source: SyntheticSource = field(init=False)

    def __post_init__(self) -> None:
        self._source = SyntheticSource(self.spec, seed=self.seed)

    @property
    def descriptor(self) -> StreamDescriptor:
        return build_descriptor(self.spec)

    def run(self, sink: PacketSink, stop: threading.Event) -> None:
        for produced in range(self.n_packets):
            if stop.is_set():
                return
            if self.fail_after is not None and produced >= self.fail_after:
                raise RuntimeError("synthetic source failure")
            if self.disconnect_after is not None and produced >= self.disconnect_after:
                raise SourceDisconnectedError("synthetic device went away")
            sink.submit(as_source_packet(self._source.next_chunk(1)))
            if self.after_packet is not None:
                self.after_packet()


def as_source_packet(chunk: PendingChunk) -> SourcePacket:
    """Split a one-packet :class:`PendingChunk` into a recorder packet.

    The rows are passed through unchanged — in particular the host arrival
    times the generator produced, which the recorder must never re-stamp
    (``AGENTS.md`` §4).
    """
    if len(chunk.packets) != 1:
        raise ValueError("a source packet carries exactly one packet row")
    payload = chunk.payloads[0][1] if chunk.payloads else None
    return SourcePacket(
        packet=chunk.packets[0],
        samples=list(chunk.samples),
        observations=list(chunk.observations),
        payload=payload,
    )
